/**
 * High-fidelity Mock & Demo Dataset for Instant Trust Fund CRM
 * Used for client presentation, Vercel demo deployment, and zero-backend preview.
 */

export const DEMO_USERS = {
  super_admin: {
    id: "admin-demo-01",
    fullName: "Syed Abdul Khader (Managing Director)",
    email: "admin@instanttrustfunds.com",
    mobile: "+91 99801 23456",
    role: "super_admin" as const,
    permissions: ["all", "manage_admins", "system_settings", "bulk_import"],
  },
  assistant_admin: {
    id: "assistant-demo-01",
    fullName: "Praveen Kumar (Senior Operations Lead)",
    email: "praveen@instanttrustfunds.com",
    mobile: "+91 98448 47836",
    role: "assistant_admin" as const,
    permissions: ["tasks", "customers:read", "applications:read", "sms:send"],
  },
  customer: {
    id: "customer-demo-01",
    fullName: "Rajesh S. Sharma",
    email: "rajesh.sharma@gmail.com",
    mobile: "+91 98801 45678",
    dob: "1988-06-15",
    role: "customer" as const,
    cibilScore: 782,
    city: "Bengaluru",
    state: "Karnataka",
  },
};

export const DEMO_APPLICATIONS = [
  {
    _id: "APP-2026-001",
    fullName: "Rajesh S. Sharma",
    mobile: "+91 98801 45678",
    productKind: "loan",
    productType: "Home Loan",
    amount: "₹45,00,000",
    bankPartner: "State Bank of India (SBI)",
    status: "Approved",
    stage: "Sanction Letter Issued",
    createdAt: "2026-10-02T10:30:00Z",
    assignedTo: "Praveen Kumar",
  },
  {
    _id: "APP-2026-002",
    fullName: "Ananya Patel",
    mobile: "+91 98234 11223",
    productKind: "loan",
    productType: "Business Loan",
    amount: "₹25,00,000",
    bankPartner: "HDFC Bank",
    status: "Pending",
    stage: "Financial Audit & GST Review",
    createdAt: "2026-10-05T14:15:00Z",
    assignedTo: "Praveen Kumar",
  },
  {
    _id: "APP-2026-003",
    fullName: "Mohammed Faheem",
    mobile: "+91 99450 78910",
    productKind: "loan",
    productType: "Loan Against Property",
    amount: "₹75,00,000",
    bankPartner: "ICICI Bank",
    status: "Pending",
    stage: "KGIS Cadastral Survey Check",
    createdAt: "2026-10-06T09:45:00Z",
    assignedTo: "Syed Abdul Khader",
  },
  {
    _id: "APP-2026-004",
    fullName: "Nazneen Banu",
    mobile: "+91 97412 34567",
    productKind: "insurance",
    productType: "Health Insurance (Family Floater)",
    amount: "₹15,00,000 Cover",
    bankPartner: "Star Health & Allied Insurance",
    status: "Approved",
    stage: "Policy Issued & Active",
    createdAt: "2026-09-28T11:00:00Z",
    assignedTo: "Praveen Kumar",
  },
  {
    _id: "APP-2026-005",
    fullName: "Kavitha Raman",
    mobile: "+91 94481 55667",
    productKind: "loan",
    productType: "Education Loan (International)",
    amount: "₹22,00,000",
    bankPartner: "Canara Bank",
    status: "Approved",
    stage: "Visa Verification Complete",
    createdAt: "2026-10-01T16:20:00Z",
    assignedTo: "Syed Abdul Khader",
  },
  {
    _id: "APP-2026-006",
    fullName: "Dr. Sandeep Hegde",
    mobile: "+91 98450 99887",
    productKind: "loan",
    productType: "Professional Equipment Loan",
    amount: "₹30,00,000",
    bankPartner: "Bank of Baroda",
    status: "Pending",
    stage: "Machinery Invoice Valuation",
    createdAt: "2026-10-06T15:00:00Z",
    assignedTo: "Praveen Kumar",
  },
  {
    _id: "APP-2026-007",
    fullName: "Suresh Gowda",
    mobile: "+91 96112 44332",
    productKind: "loan",
    productType: "Commercial Vehicle Loan",
    amount: "₹18,50,000",
    bankPartner: "Tata Motors Finance",
    status: "Approved",
    stage: "RTO Hypothecation Pending",
    createdAt: "2026-09-25T13:40:00Z",
    assignedTo: "Praveen Kumar",
  },
  {
    _id: "APP-2026-008",
    fullName: "Vidya Shree",
    mobile: "+91 98448 47836",
    productKind: "insurance",
    productType: "Life Insurance (Term Plan)",
    amount: "₹1.5 Crore Cover",
    bankPartner: "HDFC Life",
    status: "Approved",
    stage: "Medical Tele-underwriting Cleared",
    createdAt: "2026-10-04T12:10:00Z",
    assignedTo: "Syed Abdul Khader",
  },
];

export const DEMO_CUSTOMERS = [
  {
    _id: "CUST-101",
    fullName: "Rajesh S. Sharma",
    mobile: "+91 98801 45678",
    email: "rajesh.sharma@gmail.com",
    pan: "ABCPS1234F",
    aadhaar: "•••• •••• 9012",
    city: "Bengaluru",
    taluk: "Bengaluru South",
    district: "Bengaluru Urban",
    cibilScore: 782,
    source: "Website Direct",
    status: "Active Customer",
    activeLoansCount: 2,
    totalDisbursed: "₹45,00,000",
    createdAt: "2026-08-15T10:00:00Z",
  },
  {
    _id: "CUST-102",
    fullName: "Nazneen Banu",
    mobile: "+91 97412 34567",
    email: "nazneen.banu@yahoo.com",
    pan: "ABZPN5432K",
    aadhaar: "•••• •••• 4421",
    city: "Hubballi",
    taluk: "Hubballi Urban",
    district: "Dharwad",
    cibilScore: 745,
    source: "Excel Seeder (Old CRM)",
    status: "Verified Lead",
    activeLoansCount: 1,
    totalDisbursed: "₹15,00,000",
    createdAt: "2026-08-18T11:20:00Z",
  },
  {
    _id: "CUST-103",
    fullName: "Mohammed Faheem",
    mobile: "+91 99450 78910",
    email: "faheem.ent@outlook.com",
    pan: "AFZPM9988D",
    aadhaar: "•••• •••• 7731",
    city: "Belagavi",
    taluk: "Belagavi",
    district: "Belagavi",
    cibilScore: 790,
    source: "Direct Broker",
    status: "Under Review",
    activeLoansCount: 1,
    totalDisbursed: "₹75,00,000",
    createdAt: "2026-09-02T14:45:00Z",
  },
  {
    _id: "CUST-104",
    fullName: "Ananya Patel",
    mobile: "+91 98234 11223",
    email: "ananya.patel@techcorp.in",
    pan: "AXCPP4321R",
    aadhaar: "•••• •••• 1152",
    city: "Bengaluru",
    taluk: "Anekal",
    district: "Bengaluru Urban",
    cibilScore: 810,
    source: "Partner Referral",
    status: "Active Customer",
    activeLoansCount: 2,
    totalDisbursed: "₹25,00,000",
    createdAt: "2026-09-10T09:30:00Z",
  },
  {
    _id: "CUST-105",
    fullName: "Dr. Sandeep Hegde",
    mobile: "+91 98450 99887",
    email: "dr.sandeep@clinicplus.org",
    pan: "ASBPH7766M",
    aadhaar: "•••• •••• 6632",
    city: "Mangaluru",
    taluk: "Mangaluru",
    district: "Dakshina Kannada",
    cibilScore: 825,
    source: "Medical Association Drive",
    status: "High Net Worth",
    activeLoansCount: 1,
    totalDisbursed: "₹30,00,000",
    createdAt: "2026-09-15T16:15:00Z",
  },
  {
    _id: "CUST-106",
    fullName: "Kavitha Raman",
    mobile: "+91 94481 55667",
    email: "kavitha.raman@gmail.com",
    pan: "ARKPR8877S",
    aadhaar: "•••• •••• 9920",
    city: "Mysuru",
    taluk: "Mysuru",
    district: "Mysuru",
    cibilScore: 760,
    source: "Website Direct",
    status: "Active Customer",
    activeLoansCount: 1,
    totalDisbursed: "₹22,00,000",
    createdAt: "2026-09-20T10:40:00Z",
  },
  {
    _id: "CUST-107",
    fullName: "Suresh Gowda",
    mobile: "+91 96112 44332",
    email: "suresh.logistics@rediffmail.com",
    pan: "AGXPS6655L",
    aadhaar: "•••• •••• 3311",
    city: "Tumakuru",
    taluk: "Tumakuru",
    district: "Tumakuru",
    cibilScore: 715,
    source: "Fleet Transport Association",
    status: "Active Customer",
    activeLoansCount: 3,
    totalDisbursed: "₹42,00,000",
    createdAt: "2026-09-22T13:00:00Z",
  },
  {
    _id: "CUST-108",
    fullName: "Vidya Shree",
    mobile: "+91 98448 47836",
    email: "vidyashree.k@gmail.com",
    pan: "AKVPV3322T",
    aadhaar: "•••• •••• 5543",
    city: "Shivamogga",
    taluk: "Bhadravati",
    district: "Shivamogga",
    cibilScore: 770,
    source: "Website Direct",
    status: "Verified Lead",
    activeLoansCount: 1,
    totalDisbursed: "₹8,00,000",
    createdAt: "2026-09-25T15:20:00Z",
  },
];

export const DEMO_CHARTS_DATA = {
  monthly: [
    { month: "May 2026", applications: 38, disbursed: 29 },
    { month: "Jun 2026", applications: 46, disbursed: 36 },
    { month: "Jul 2026", applications: 58, disbursed: 47 },
    { month: "Aug 2026", applications: 72, disbursed: 59 },
    { month: "Sep 2026", applications: 94, disbursed: 81 },
    { month: "Oct 2026", applications: 128, disbursed: 104 },
  ],
  smsChart: [
    { day: "Oct 01", sent: 1420, delivered: 1395, failed: 25 },
    { day: "Oct 02", sent: 980, delivered: 968, failed: 12 },
    { day: "Oct 03", sent: 1850, delivered: 1820, failed: 30 },
    { day: "Oct 04", sent: 1230, delivered: 1215, failed: 15 },
    { day: "Oct 05", sent: 2100, delivered: 2068, failed: 32 },
    { day: "Oct 06", sent: 1670, delivered: 1642, failed: 28 },
    { day: "Oct 07", sent: 2450, delivered: 2418, failed: 32 },
  ],
  loanDist: [
    { name: "Home Loans", value: 42 },
    { name: "Business Loans", value: 28 },
    { name: "Loan Against Property", value: 16 },
    { name: "Personal Loans", value: 14 },
  ],
  insDist: [
    { name: "Health Insurance", value: 48 },
    { name: "Life & Term", value: 26 },
    { name: "Motor Insurance", value: 18 },
    { name: "Property & Marine", value: 8 },
  ],
};

export const DEMO_TASKS = [
  {
    id: "TSK-101",
    title: "Verify Bhoomi RTC & Cadastral Boundaries for Property Loan Ref #LAP-2026-003",
    customer: "Mohammed Faheem",
    priority: "Urgent",
    status: "Pending",
    due: "Today, 5:00 PM",
    category: "GIS & Legal Verification",
  },
  {
    id: "TSK-102",
    title: "Collect Audited FY25-26 Balance Sheet & GST returns for Business Loan",
    customer: "Ananya Patel",
    priority: "High",
    status: "In Progress",
    due: "Tomorrow, 12:00 PM",
    category: "Financial Underwriting",
  },
  {
    id: "TSK-103",
    title: "Issue Final Sanction Letter & Schedule Agreement Signing with SBI Bank Manager",
    customer: "Rajesh S. Sharma",
    priority: "High",
    status: "Pending",
    due: "Oct 09, 2026",
    category: "Disbursement",
  },
  {
    id: "TSK-104",
    title: "Audit DLT SMS Sender Headers (TRAI Compliance Renewal)",
    customer: "System Maintenance",
    priority: "Normal",
    status: "Completed",
    due: "Oct 06, 2026",
    category: "Compliance",
  },
  {
    id: "TSK-105",
    title: "Follow up on Health Insurance Portability docs from Star Health",
    customer: "Nazneen Banu",
    priority: "Normal",
    status: "In Progress",
    due: "Oct 10, 2026",
    category: "Insurance Ops",
  },
];

export const DEMO_NOTIFICATIONS = [
  {
    id: "NOTIF-1",
    title: "High-Value Loan Sanction Approved",
    description: "State Bank of India approved ₹45,00,000 Home Loan for Rajesh S. Sharma.",
    timestamp: "12 minutes ago",
    unread: true,
    tone: "success",
  },
  {
    id: "NOTIF-2",
    title: "New Customer Application Received",
    description: "Dr. Sandeep Hegde applied for ₹30,00,000 Professional Equipment Loan.",
    timestamp: "45 minutes ago",
    unread: true,
    tone: "info",
  },
  {
    id: "NOTIF-3",
    title: "DLT SMS Campaign Delivered",
    description: "Campaign 'Festive Gold & Home Loan Rates' sent to 2,450 verified leads.",
    timestamp: "2 hours ago",
    unread: false,
    tone: "default",
  },
  {
    id: "NOTIF-4",
    title: "Property Survey Report Available",
    description: "KGIS survey record for Plot 23/1A Bangalore Urban verified successfully.",
    timestamp: "4 hours ago",
    unread: false,
    tone: "success",
  },
];

export const DEMO_REFERRALS = [
  {
    id: "REF-001",
    agentName: "Basavaraj Patil",
    firm: "Patil Realty Consultants",
    city: "Hubballi",
    leadsCount: 38,
    sanctionedAmount: "₹2.4 Crores",
    commissionRate: "0.65%",
    payoutEarned: "₹1,56,000",
    status: "Active Tier 1",
  },
  {
    id: "REF-002",
    agentName: "S. Venkatesh & Associates",
    firm: "Chartered Accountants",
    city: "Bengaluru",
    leadsCount: 52,
    sanctionedAmount: "₹4.1 Crores",
    commissionRate: "0.75%",
    payoutEarned: "₹3,07,500",
    status: "Premier Platinum",
  },
  {
    id: "REF-003",
    agentName: "Meenakshi Sundaram",
    firm: "Sundaram Financial Services",
    city: "Mysuru",
    leadsCount: 24,
    sanctionedAmount: "₹1.2 Crores",
    commissionRate: "0.50%",
    payoutEarned: "₹60,000",
    status: "Active Tier 2",
  },
  {
    id: "REF-004",
    agentName: "Imran Khan",
    firm: "Apex Auto Dealership",
    city: "Belagavi",
    leadsCount: 19,
    sanctionedAmount: "₹95 Lakhs",
    commissionRate: "0.50%",
    payoutEarned: "₹47,500",
    status: "Active Tier 2",
  },
];

export const DEMO_PROPERTIES = [
  {
    id: "PROP-001",
    title: "Prime Commercial Land Parcel — 2.4 Acres",
    surveyNumber: "Survey No 23/1A",
    taluk: "Bengaluru South",
    district: "Bengaluru Urban",
    village: "Begur",
    marketValue: "₹14.5 Crores",
    loanEligibility: "Up to ₹10 Crores (LAP)",
    status: "Verified by KGIS",
    ownerName: "Sharma Holdings & Estates",
    coordinates: { lat: 12.8812, lng: 77.6288 },
    features: ["100 ft Main Road Facing", "Clear Title", "A-Khata Registered", "BMRDA Approved"],
  },
  {
    id: "PROP-002",
    title: "Industrial Logistics Warehouse & Plot",
    surveyNumber: "Survey No 142/C",
    taluk: "Hubballi Rural",
    district: "Dharwad",
    village: "Tarihal Industrial Area",
    marketValue: "₹6.8 Crores",
    loanEligibility: "Up to ₹4.5 Crores",
    status: "Verified by KGIS",
    ownerName: "Deccan Transport Logistics",
    coordinates: { lat: 15.3647, lng: 75.1240 },
    features: ["KIADB Allotment", "Heavy Power 150 HP", "Immediate Sanction Eligible"],
  },
  {
    id: "PROP-003",
    title: "Residential Development Land — 18,000 Sq Ft",
    surveyNumber: "Survey No 88",
    taluk: "Mysuru Taluk",
    district: "Mysuru",
    village: "Vijayanagar 4th Stage",
    marketValue: "₹5.2 Crores",
    loanEligibility: "Up to ₹3.8 Crores",
    status: "Verified by KGIS",
    ownerName: "Mysuru Builders Consortium",
    coordinates: { lat: 12.2958, lng: 76.6394 },
    features: ["MUDA Approved", "Corner Plot", "High Resale Appreciation"],
  },
  {
    id: "PROP-004",
    title: "Agricultural Farm Estate with Water Rights",
    surveyNumber: "Survey No 312/2",
    taluk: "Shivamogga",
    district: "Shivamogga",
    village: "Gajanur",
    marketValue: "₹3.4 Crores",
    loanEligibility: "Up to ₹2.0 Crores (Agri Loan)",
    status: "Verified by KGIS",
    ownerName: "Gowda Agro Plantation",
    coordinates: { lat: 13.9299, lng: 75.5681 },
    features: ["Arecanut & Spices Yield", "River Water Pump Connection", "Bhoomi RTC Clear"],
  },
];
